###
GET http://localhost:8080/api/locations
Accept: application/json

###
POST http://localhost:8080/api/locations
Content-Type: application/json
Accept: application/json

{
  "name": "Herceg-szigetek",
  "lat": 40.5233,
  "lon": 29.0522
}

### FELÜLÍRJA az összes adattagot/attribútomot, ha nincs benne adott elágazás.
PUT http://localhost:8080/api/locations/2
Content-Type: application/json
Accept: application/json

{
  "name": "Endor"
}

###
DELETE http://localhost:8080/api/locations/2








