### TELJES LISTA
GET http://localhost:8080/api/locations
Accept: application/json

### HIBAKÓD:500 -Nem létező ID- KEZELVE:404-re
GET http://localhost:8080/api/locations/500
Accept: application/json

### STÁTUSZKÓD-KEZELVE 200-as 201-re
POST http://localhost:8080/api/locations
Content-Type: application/json
Accept: application/json

{
  "name": "Herceg-szigetek",
  "lat": 40.5233,
  "lon": 29.0522
}

### Validáció
POST http://localhost:8080/api/locations
Content-Type: application/json
Accept: application/json

{
  "name": "",
  "lat": -90.5233,
  "lon": -180.0522
}


### FELÜLÍRJA az összes adattagot/attribútomot, ha nincs benne adott elágazás.
PUT http://localhost:8080/api/locations/2
Content-Type: application/json
Accept: application/json

{
  "name": "Endor"
}

### STÁTUSZKÓD-KEZELVE 200-as 201-re
DELETE http://localhost:8080/api/locations/1








